### ISSUE TITLE
How to increase font size globally?

### ISSUE THREAD

**Issue by kyyberi** [apinf/meteor-oembed-blog#40]
The text size is rather tiny especially when used with mobile devices. How to change font size larger so that it affects all text styles?

# Problem

I used this component in http://apiops.net:3000/ draft page for APIOps community. The content was laid out nicely, but when I was looking at the page from phone (iPhone6 or Honor8) the text was really tiny, nearly impossible to read. This was the feedback from Twitter as well. 

![c4dxeg9wyaevpwu jpg_large](https://cloud.githubusercontent.com/assets/1927158/23120336/9baa2c6c-f764-11e6-8506-d05dc36c5ed5.jpeg)

The pic above  contains extra content not provided by the component, but I've used same html elements in own additions. In addition, the same problem is found in component driven content as well. 

It feels like the responsiveness of the design/layout is not working properly yet. Yes, it limits the amount of parallel blocks in content listing, but font size is not readable.

**Comment by bajiat** [comment]
@kyyberi Describe the problem or steps to reproduce
